name: levelingplugin
version: '1.0-SNAPSHOT'
main: pl.r3.levelingplugin.LevelingPlugin
api-version: '1.20'
commands:
  poziomy:
    description: Open the LVL Rewards GUI
    usage: /poziomy
    aliases: /lvl
    permission: yourplugin.command.opengui
